spring.application.name=java_dbTest
spring.datasource.url=jdbc:postgresql://localhost:5432/dbTest_1
spring.datasource.username=postgres
spring.datasource.password=

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true